# Generated by Django 3.2 on 2021-05-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=100, null=True)),
                ('trainer_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('trainer_title', models.CharField(max_length=100, null=True)),
                ('trainer_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('trainer_linkedin', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('event_category', models.CharField(choices=[('Webinar', 'webinar'), ('Seminar', 'seminar'), ('Workshop', 'workshop')], default='Workshop', max_length=20, null=True)),
                ('event_audience', models.CharField(choices=[('Umum', 'umum'), ('Guru', 'guru')], default='Umum', max_length=20, null=True)),
                ('ticket_price', models.IntegerField(default=0, null=True)),
                ('ticket_available', models.IntegerField(default=0, null=True)),
                ('event_summary', models.CharField(max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, default='2021-05-19', null=True)),
                ('event_start_time', models.TimeField(blank=True, default='08:30', null=True)),
                ('event_finish_time', models.TimeField(blank=True, default='14:30', null=True)),
                ('event_venue', models.CharField(max_length=100, null=True)),
                ('event_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('event_image_header', models.ImageField(blank=True, null=True, upload_to='')),
                ('event_detail', models.CharField(max_length=500, null=True)),
                ('event_contact_person', models.CharField(max_length=200, null=True)),
                ('event_facilities', models.ManyToManyField(blank=True, to='event_app.Facility')),
                ('event_trainer', models.ManyToManyField(blank=True, to='event_app.Trainer')),
            ],
        ),
    ]
