# Generated by Django 3.2 on 2021-05-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_trainer_trainer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='icon',
            field=models.CharField(default='bookmark', max_length=20, null=True),
        ),
    ]
